### ISSUE TITLE
Readme type-o

### ISSUE THREAD

**Issue by jmancine** [falconair/nodefix#36]
'nodefix' seems to have changed names to 'fix' ? 
http://search.npmjs.org/#/fix

On the readme -- this is old?
npm install nodefix

**Comment by falconair** [comment]
Frankly I don't even remember when I changed it. I'll change it back to avoid confusion. I'll probably eventually create a derivative of this project and call it fix.js, but better not to muck up what exists already.

Thanks for checking.
